# Generated by Django 4.0.2 on 2022-02-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('nrgestiune', models.IntegerField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('varsta', models.CharField(max_length=3)),
                ('gen', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('observatii', models.TextField()),
                ('data_adaugarii', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
