# Generated by Django 4.0.2 on 2022-03-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamente', '0001_initial'),
        ('pacienti', '0003_alter_pacient_observatii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_expirare', models.DateField()),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamente.medicament')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacienti.pacient')),
            ],
        ),
    ]
