# Generated by Django 4.0.2 on 2022-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numemedicament', models.CharField(max_length=40)),
                ('stoc', models.IntegerField()),
                ('unitate', models.CharField(choices=[('comprimate', 'comprimate'), ('flacoane', 'flacoane')], max_length=10, null=True)),
                ('data_expirarii', models.DateField()),
            ],
        ),
    ]
